config/routes.rb
MuseumApp::Application.routes.draw do
  root "paintings#index"
    resources :paintings
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :paintings

  def self.search_for(query)
    where('name LIKE :query', query: "%#{query}%") 
  end
end

app/models/museum.rb
class Museum < ActiveRecord::Base
  has_many :paintings
  has_many :artists, through: :paintings

    def self.search_for(query)
    where('name LIKE :query', query: "%#{query}%") 
  end
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  belongs_to :artist
  belongs_to :museum


  def self.search_for(query)
    where('title LIKE :query', query: "%#{query}%") 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  def index
    @paintings = params[:q] ? Painting.search_for(params[:q]) : Painting.all
    @artists = params[:q] ? Artist.search_for(params[:q]) : Artist.all
    @museums = params[:q] ? Museum.search_for(params[:q]) : Museum.all
  end

  def show
    @painting = Painting.find params[:id]
  end

  def new

    @painting = Painting.new
  end

  def create
    @artist = Artist.find_or_create_by_name()
    @Museum = Museum.find_or_create_by_name()
    @painting = Painting.new safe_params
  end
  # def create
  #   @movie = Movie.new safe_params
  #   if @movie.save
  #     flash[:notice] =  "Movie saved successfully"
  #     redirect_to @movie
  #   else
  #     render 'new'
  #   end
  # end

  private

  def safe_params
    params.require(:painting).permit(:title, :url)
  end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MuseumApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/paintings/_list.html.erb
<% @paintings.each do |painting| %>
  <section>
    <header>
     <b><%= link_to painting.title, painting %></b>
    </header>
  </section>
  <br/>
<% end %>

app/views/paintings/_list_artists.html.erb
<% @artists.each do |artist| %>
  <section>
    <header>
     <b><%= artist.name%></b>
    </header>
  </section>
  <br/>
<% end %>

app/views/paintings/_list_museums.html.erb
<% @museums.each do |museum| %>
  <section>
    <header>
     <b><%= museum.name %></b>
    </header>
  </section>
  <br/>
<% end %>

app/views/paintings/create.html.erb
<h1>Paintings#create</h1>
<p>Find me in app/views/paintings/create.html.erb</p>

app/views/paintings/index.html.erb
<h1>Paintings#index</h1>
<p>Find me in app/views/paintings/index.html.erb</p>


<%= button_to "Add Painting", new_painting_path, method: :get %>

<%= form_tag '/', method: :get do %>
  <%= search_field_tag :q, params[:q] %>
  <%= submit_tag "Search" %>
<% end %>

<%= render 'list' %>
<%= render 'list_artists' %>
<%= render 'list_museums' %>

app/views/paintings/new.html.erb
<%= form_for [@painting] do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title%>

    <%= f.label :url %>
    <%= f.text_field :url %>
  </p>
  <%= f.submit %>
<% end %>

<%= form_for @artist do |f| %>
  <%= f.label :artist %>
  <%= f.text_field :artist %>
<% end %>

<%= form_for @museum do |f| %>
  <%= f.label :museum %>
  <%= f.text_field :museum %>
<% end %>

app/views/paintings/show.html.erb
<h1> <%= @painting.title %> </h1>
By: <%= @painting.artist.name %> <br>
Location: <%= @painting.museum.name %> <br>
<%= image_tag("#{@painting.url}") %>